import {
  BoldExtension,
  ItalicExtension,
  HeadingExtension,
  StrikeExtension,
  CodeExtension,
  BlockquoteExtension,
  BulletListExtension,
  OrderedListExtension,
  TaskListExtension,
  LinkExtension,
  ImageExtension,
  HorizontalRuleExtension,
  HistoryExtension,
  MarkdownExtension,
  TrailingNodeExtension,
} from "remirror/extensions";

export const getExtensions = () => [
  new HistoryExtension({}),
  new BoldExtension({}),
  new ItalicExtension(),
  new StrikeExtension(),
  new HeadingExtension({}),
  new CodeExtension(),
  new BlockquoteExtension(),
  new BulletListExtension({ enableSpine: true }),
  new OrderedListExtension(),
  new TaskListExtension(), // checklists
  new LinkExtension({ autoLink: true }),
  new ImageExtension({ enableResizing: true }),
  new HorizontalRuleExtension({}),
  new TrailingNodeExtension({}),
  new MarkdownExtension({ copyAsMarkdown: true }),
];
